name = "Mine Detector Fixes"
author = "Dart"
prefix = "mdf"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_mdf_ca.paa",
    "logo_mdf_over_ca.paa",
    "LICENSE.md",
    "README.md"
]
exclude = [
    "*.psd"
]

[properties]
author = "DartRuffian"
url = "https://github.com/DartRuffian/MineDetectorFixes"